### ISSUE TITLE
Sampling in statsd implementation

### ISSUE THREAD

**Issue by augi** [avast/metrics#4]
If some metric is updated very frequently, you can easily overload the statsd server. So it would be useful to have support for sampling in the statsd implementation.

Not sure, how it should be configured. E.g. we could specify sampling rate for all the metrics globally - it would be very straightforward.

**Comment by jendakol** [comment]
I got your point. PR welcomed :-)

**Comment by mixalturek** [comment]
Implemented in #22, version 2.1.0.
