### ISSUE TITLE
Fix JDK11 build

### ISSUE THREAD

**Issue by augi** [avast/metrics#47]
After migration to build using JDK11 (required by TravisCI), we are getting this error:
```
[error] /home/travis/build/avast/metrics/core/src/main/java/com/avast/metrics/core/jvm/JvmMetrics.java:7:1: package sun.management is not visible
[error]   (package sun.management is declared in module java.management, which does not export it to the unnamed module)
[error] import sun.management.ManagementFactoryHelper;
```

I tried to solve it using [this line of code](https://github.com/avast/metrics/blob/master/build.sbt#L10) but it didn't help so a need of an sbt guru is probably required.
```
javaOptions ++= Seq("--add-exports", "java.management/sun.management=ALL-UNNAMED"),
```

**Comment by sideeffffect** [comment]
here are some relevant guides I've found on the web, you may have read the already

what is the error that you're getting? Is this switch (`--add-exports java.management/sun.management=ALL-UNNAMED`) broken just in `sbt`, or it doesn't work in general?

https://blog.codefx.org/java/java-9-migration-guide/#Illegal-Access-To-Internal-APIs
https://blog.codefx.org/java/java-11-migration-guide/
https://blog.codefx.org/java/five-command-line-options-hack-java-module-system/

**Comment by augi** [comment]
I've read all the articles. I just don't know how to add this parameter in `sbt`.

The error is in my first post, and also can be seen in the TravisCI log.

**Comment by hunterlodge** [comment]
add it as jvm args
